cifar_10:
  batch_size: 64
  num_outputs: 10
  num_labeled: 4000

MixMatchTrainer:
  n_steps: 10000
  K: 2

  lambda_u:
    lambda_u_max: 75
    step_top_up: 8000 # 16000

  steps_validation: 500 # steps to print validation losses and accuracy
  steps_checkpoint: 5000

  optimizer: 'adam'
  adam:
    lr: 0.002
    weight_decay: 0.0004
  sgd:
    lr: 0.03
    momentum: 0.9
    weight_decay: 0.0005
    lr_decay_steps: {}


WideResNet:
  depth: 28
  k: 2
  n_out: 10