cifar_10:
  batch_size: 64
  num_outputs: 10
  num_labeled: 250

MixMatchTrainer:
  n_steps: 100
  K: 2
  lambda_u_max: 75
  steps_validation: 10 # steps to print validation losses and accuracy
  step_top_up: 16000
  optimizer: 'sgd'
  adam:
    lr: 0.002
    weight_decay: 0.0004
  sgd:
    lr: 0.1
    momentum: 0.9
    weight_decay: 0.0005


WideResNet:
  depth: 28
  k: 2
  n_out: 10